### ISSUE TITLE
certificate signed by unknown authority

### ISSUE THREAD

**Issue by aviau** [peter-edge/lion-go#2]
Hello!

I am getting the following error when getting anything that is hosted on go.pedge.io:

```
package go.pedge.io/lion: unrecognized import path "go.pedge.io/lion" (https fetch: Get https://go.pedge.io/lion?go-get=1: x509: certificate signed by unknown authority)
```

Cheers,

**Comment by peter-edge** [comment]
Well shoot, I'll need to fix this. Thanks for the heads up.

**Comment by JesseFinch** [comment]
> Well shoot, I'll need to fix this. Thanks for the heads up.

How is it going?

**Comment by bsElyes** [comment]
hey guys , i got the same problem

**Comment by peter-edge** [comment]
Sorry for the delay - I just spent a few hours redoing the deployment, this should be fixed now, reopen if not.
